<a href="https://colab.research.google.com/github/delhoya/Book/blob/main/%EB%AA%A8%EB%91%90%EC%9D%98_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_with_%ED%8C%8C%EC%9D%B4%EC%8D%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
from google.colab import drive
drive.mount('/content/drive')


import numpy as np
dataset = np.loadtxt("/content/drive/My Drive/Colab Notebooks/모두의 데이터 분석 with 파이썬/pima-indians-diabetes.csv" , delimiter=",")
print(dataset)



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[  6. 148.  72.   1.]
 [  1.  85.  66.   0.]
 [  8. 183.  64.   1.]
 ...
 [  1.  89.  24.   0.]
 [  1. 173.  74.   1.]
 [  1. 109.  38.   0.]]
